spring:
 application:
   name: gateway-server
 cloud:
  gateway:
    discovery:
     locator:
       enabled: false #不通过直接通过discover找到server进行配置
# 直接通过discover找到server进行配置
#       predicates: [
#          {'name':'Path','args':{"pattern":"'/'+serviceId +'/**'"}}, #指定路径规则
#          {'name':'Host','args':{"pattern":"'localhost'"}} #指定host
#          ]
#       lower-case-service-id: true
#    filter:
#      - JwtFiliter
    globalcors:
      cors-configurations:
        '[/**]':
           allowedOrigins: ['*']
           allowedMethods: ['*']
           allowedHeaders: ['*']
           allowCredentials: true
 rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
server:
  port: 9094


management:
  endpoints:
    web:
      exposure:
        include: '*'

route:
  routeFile: D:\project\myproj\myTempSpring\spring-gateway-service2\src\main\resources\route.json




