spring:
  redis:
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制
    database: 0
    timeout: 1000
    password: sOd3bZBFgdVyGRWC
    host: 10.42.0.23
    port: 6379
logging:
  level:
   com.oycl.zz.dao.MCodeMapper: debug # 改成你的mapper文件所在包路径
