eureka:
  client:
    serviceUrl:
      #defaultZone: http://prod1:9090/eureka/,http://prod2:9092/eureka/
      defaultZone: http://localhost:9090/eureka/
server:
  port: 8010
  servlet:
    context-path: /api
spring:
  application:
    name: main-api

# 打开feign对hystrix的支持
feign:
  hystrix:
    enabled: true

#配置ribbon time-out
main-service:
  ribbon:
   ConnectTimeout: 250
   ReadTimeout: 1000

# 配置hystrix
hystrix:
  threadpool:
    default:
      coreSize: 10  #线程池核心线程数
  command:
    #IService#hello(): 设置某一个接口 default: 设置全部接口
    default:
      execution:
        isolation:
          strategy: Thread #隔离策略，默认是Thread, 可选Thread｜Semaphore
          thread:
            timeoutInMilliseconds: 1000 #命令执行超时时间 超时时间
            interruptOnTimeout: true #发生超时是是否中断，默认true
        timeout:
          enabled: true #执行是否启用超时，默认启用true
      circuitBreaker:
        requestVolumeThreshold: 3  #当在配置时间窗口内达到此数量后，进行短路。默认20个
        sleepWindowInMilliseconds: 5  #短路多久以后开始尝试是否恢复，默认5s
        errorThresholdPercentage: 50%  #出错百分比阈值，当达到此阈值后，开始短路。默认50%