spring:
  profiles:
    active: local
  application:
    name: data-server
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://${dbhost}/test?serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8
      username: ${dbuser}
      password: ${dbpw}
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: creditHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
server:
  port: 9096
---
spring:
  profiles: dev
dbhost: sh-cdb-fhama989.sql.tencentcdb.com:63156
dbuser: root
dbpw: jHnXk31UXZasddf
---
spring:
  profiles: local
dbhost: sh-cdb-fhama989.sql.tencentcdb.com:63156
dbuser: root
dbpw: jHnXk31UXZasddf

