zuul:
  sensitiveHeaders:
  #ignoredHeaders: Cookies,Set-Cookie
  prefix: /scf
  routes:
    # 登录主工程
    main-api:
      path: /main/**
      serviceId: main-api
  ratelimit:
    enabled: true
    behind-proxy: true  #代理之后
    default-policy: #可选 - 针对所有的路由配置的策略，除非特别配置了policies
      limit:  10 #每个刷新时间窗口对应的请求数量限制
      refresh-interval: 1 #刷新时间窗口的时间，默认值 (秒)
      type:
        - ORIGIN
        - URL
        - USER

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#eureka 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
    heathcheck:
      enable: true
  instance:
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 30
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 10
server:
  port: 8661
spring:
  application:
    name: zuul-service
