spring:
  profiles:
    active: prod2
  application:
    name: eureka
server:
  port: 9092
eureka:
  instance:
    hostname: prod2
  client:
    register-with-eureka: true
    fetch-registry: true
    com.oycl.service-url:
      defaultZone: http://prod1:9090/eureka/