spring:
  application:
    name: eureka-service
server:
  port: 9090
eureka:
  instance:
    hostname: localhost
    metadata-map:
      username: kasaya
      password: kasaya
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env
