spring:
  profiles:
    active: prod1
  application:
    name: eureka
server:
  port: 9090
eureka:
  instance:
    hostname: prod1
  client:
    register-with-eureka: true
    fetch-registry: true
    com.oycl.service-url:
      defaultZone: http://prod2:9092/eureka/