spring:
  application:
    name: eureka-com.oycl.service
server:
  port: 9090
eureka:
  instance:
    hostname: localhost
    metadata-map:
      username: kasaya
      password: kasaya

  client:
    register-with-eureka: true
    fetch-registry: true
    com.oycl.service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/