---
spring:
  profiles:
    active: @profiles.active@
  security:  #httpbasic用户名密码配置
    user:
      name: kasaya
      password: kasaya
  rabbitmq:  #mq配置
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud
  cloud:
    bus:
      trace:
        enabled: true
#endpoint
management:
  endpoint:
    httptrace:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ['*'] #开启所有端点 httptrace <-路由追踪
    enabled-by-default: true
  server:
    servlet:
      context-path: /

server:
  port: 9093

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.url}
      #获取eureka 注册列表时间
    registry-fetch-interval-seconds: 10
      #上报给eureka时间
    instance-info-replication-interval-seconds: 10
  instance:
    #健康检查页面
    health-check-url-path: ${management.server.servlet.context-path}/actuator/health
      #状态页面
    status-page-url-path: ${management.server.servlet.context-path}/actuator/status

---
#本地环境启用native环境，扫描本地文件
spring:
  profiles: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native: #从本地拉取环境
          clone-on-start: true
          force-pull: true
          timeout: 300 #链接超时时间
          #search-locations: file:///D:/project/config-file/{application}
          search-locations: file:///C:/Users/cango/config-server-file/{application}
          #search-locations: ${user.home}/config-server-file/{application}
          #resource下
          #         search-locations: classpath:/scf-config/
          #linux绝对路径下
  #         search-locations: file://apps/vdp/cofig

#重要！！！
#关于SSH KEY， 需要在config—service生成的 ssh key 放到 git 库当中，并且手动链接一次生成konw_host文件
#因为spring boot 默认去读~/.ssh/know_host中的配置
#注册中心地址
eureka:
  url:  http://localhost:9090/eureka/

---
#dev环境配置
spring:
  profiles: dev
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #从本地拉取环境
          clone-on-start: true
          force-pull: true
          timeout: 300 #链接超时时间
          uri: git@github.com:kasaya/config-file-lib.git
          #uri:  http://172.17.32.3/scf-service/scf-config-server.git  http模式
          search-paths: '{application}'
#注册中心地址
eureka:
  url:  http://localhost:9090/eureka/